# Generated by Django 2.2.6 on 2019-12-09 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('New', 'New'), ('Crossover', 'Crossover'), ('Sport', 'Sport')], max_length=15)),
                ('slug', models.SlugField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('power', models.IntegerField()),
                ('volume', models.FloatField()),
                ('max_speed', models.IntegerField()),
                ('acceleration', models.FloatField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='car_image')),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Category')),
            ],
        ),
    ]
